modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MPL V2"

[[mods]]
modId = "slotlock"
version = "${version}"
displayName = "SlotLock"
authors = "cnlimiter"
description = '''
Lock slots!
'''
logoFile = "icon.png"

[[dependencies.slotlock]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.slotlock]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "slotlock.mixins.json"
